/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class diandian_myapplication_MainActivity */

#ifndef _Included_diandian_myapplication_MainActivity
#define _Included_diandian_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     diandian_myapplication_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_diandian_myapplication_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
